## John Paige
# A bunch of commands for LaTeX and RMarkdown

from talon.voice import Word, Context, Key, Rep, Str, press
import time

ctx = Context('latex', func=lambda app, win: app.bundle in ('TeXShop', 'org.rstudio.RStudio'))

ctx.keymap({
  
    #### miscellaneous
    'dashalls': '\\\\', 

    #### basic math
    'and equals': ' &= ', 
    'dandy': ' && ', 
    'lessqual': ' <= ', 
    'grayqual': ' >= ', 
    'less': ' < ', 
    'gray': ' > ', 
    "math (propto | proper | prop)": " \\propto ", 
    "math (approx | prox)": " \\approx ", 
    'math vert': ' \\vert ', 
    'dadolly': ['$$', Key('left')], 
    'dadollies': ['$$$$', Key('left'), Key('left')], 
    'duster': ' * ', 
    'divvy': ' / ', 
    'see dot': ' \cdot ', 
    
    #### other math
    'math in': ' \\in ', 
    'math knee': ' \\ni ', 
    'math subset': ' \\subset ', 
    'math superset': ' \\supset ', 
    'math cup': ' \\cup ', 
    'math cap': ' \\subset ', 
    'math lessqual': ' \\leq ', 
    'math grayqual': ' \\geq ', 
    
    "math int": " \\int", 
    "math infinity": " \\infty", 
    "math vert": " \\vert ", 
    "math sum": " \\sum", 
    "math some": " \\sum", 
    "math prod": " \\prod", 
    "math sim": " \\sim ", 
    "math space": "~", 
    "math page": "\\newpage", 
    "math float barrier": " \\FloatBarrier", 
    "math dot": " \\dot ", 
    "math circ": "\\circ ", 
    "math centering": "\\centering", 
    "math (deaf | equiv)": " \\equiv ", 
    "math banquall": " \\neq ", 
    "math times": " \\times ", 
    "math approximate": " \\approx ", 
    "math left": " \\left ", 
    "math right": " \\right ", 
    "math item": " \\item ", 
    
    "rig prex": ["\\left ( \\right )", Key('left'), Key('left'), Key('left'), 
                 Key('left'), Key('left'), Key('left'), Key('left'), Key('left'), 
                 Key('left'), Key('space')], 
    "rig bracks": ["\\left [] \\right ]", Key('left'), Key('left'), Key('left'), 
                   Key('left'), Key('left'), Key('left'), Key('left'), Key('left'), 
                   Key('left'), Key('space')], 
    "rig kirk": ["\\left \\{ \\right \\}", Key('left'), Key('left'), Key('left'), 
                 Key('left'), Key('left'), Key('left'), Key('left'), Key('left'), 
                 Key('left'), Key('left'), Key('space')], 
    "rig abs": ["\\left | \\right |", Key('left'), Key('left'), Key('left'), 
                Key('left'), Key('left'), Key('left'), Key('left'), Key('left'), 
                Key('left'), Key('space')], 
    
    'dander grayqual': ' &\\geq ', 
    'dander lessqual': ' &\\leq ', 
    'dander banqual': ' &\\neq ', 
    'dander qual': ' &= ', 
    'dander less': ' &< ', 
    'dander gray': ' &> ', 
    'dander prox': ' &\\approx ', 
    'dander (prop | proper | propto)': ' &\\propto ', 
    
    #### greek symbols
    "math sky": " \\chi ", 
    "math kai": " \\chi ", 
    'math ksigh': '\\xi ', 
    'math ksee': '\\xi ', 
    "math fee": " \\phi ", 
    "math phi": " \\phi ", 
    "math var fee": " \\varphi ", 
    "math varphi": " \\varphi ", 
    "math omega": " \\omega ", 
    "math eta": " \\eta ", 
    "math new": " \\nu ", 
    "math alpha": " \\alpha ", 
    "math data": " \\beta ", 
    "math beta": " \\beta ", 
    "math pie": " \\pi ", 
    "math lambda": " \\lambda ", 
    "math mu": " \\mu ", 
    "math row": " \\rho ", 
    "math ro": " \\rho ", 
    "math sigh": " \\psi ", 
    "math tao": " \\tau ", 
    "math towel": " \\tau ", 
    "math theta": " \\theta ", 
    "math var theta": " \\vartheta ", 
    "math far theta": " \\vartheta ", 
    "math up": " \\upsilon ", 
    "math upsilon": " \\upsilon ", 
    "math zeta": " \\zeta ", 
    "math sigma": " \\sigma ", 
    "math delta": " \\delta ", 
    "math gamma": " \\gamma ", 
    "math kappa": " \\kappa ", 
    "math epsilon": " \\epsilon ", 
    "math var epsilon": " \\varepsilon ", 
    "math eps": " \\eps ", 
    "math apps": " \\eps ", 
    "math epps": " \\eps ", 
    
    "champy sky": " \\Chi ", 
    "champy kai": " \\Chi ", 
    'champy ksigh': ' \\Xi ', 
    'champy ksee': ' \\Xi ', 
    "champy fee": " \\Phi ", 
    "champy phi": " \\Phi ", 
    "champy var fee": " \\Varphi ", 
    "champy varphi": " \\Varphi ", 
    "champy omega": " \\Omega ", 
    "champy eta": " \\Eta ", 
    "champy new": " \\Nu ", 
    "champy alpha": " \\Alpha ", 
    "champy data": " \\Beta ", 
    "champy beta": " \\Beta ", 
    "champy pie": " \\Pi ", 
    "champy lambda": " \\Lambda ", 
    "champy mu": " \\Mu ", 
    "champy row": " \\Rho ", 
    "champy ro": " \\Rho ", 
    "champy sigh": " \\Psi ", 
    "champy tao": " \\Tau ", 
    "champy towel": " \\Tau ", 
    "champy theta": " \\Theta ", 
    "champy var theta": " \\Vartheta ", 
    "champy far theta": " \\Vartheta ", 
    "champy up": " \\Upsilon ", 
    "champy upsilon": " \\Upsilon ", 
    "champy zeta": " \\Zeta ", 
    "champy sigma": " \\Sigma ", 
    "champy delta": " \\Delta ", 
    "champy gamma": " \\Gamma ", 
    "champy kappa": " \\Kappa ", 
    "champy epsilon": " \\Epsilon ", 
    "champy var epsilon": " \\Varepsilon ", 
    "champy eps": " \\Eps ", 
    "champy apps": " \\Eps ", 
    "champy epps": " \\Eps ", 
    
    #### latex commands with inputs
    'tecker ref': ['\\ref{}', Key('left')], 
    'tecker (tbf | textbf)': ['\\textbf{}', Key('left')], 
    'tecker (mbf | mathbf)': ['\\mathbf{}', Key('left')],
    'tecker site (teek | tea)': ['\\citet{}', Key('left')], 
    'tecker site (pea | pooch)': ['\\citep{}', Key('left')], 
    'tecker site': ['\\cite{}', Key('left')], 
    'tecker caption': ['\\caption{}', Key('left')], 
    'tecker ellis tn line': ['\\lstinline{}', Key('left')], 
    'tecker ellis tea inline': ['\\lstinline{}', Key('left')], 
    'tecker ellis t inline': ['\\lstinline{}', Key('left')], 
    'tecker label': ['\\label{}', Key('left')], 
    'tecker hat': ['\\hat{}', Key('left')], 
    'tecker new command': ['\\newcommand{}', Key('left')], 
    'tecker wide hat': ['\\widehat{}', Key('left')], 
    'tecker tilde': ['\\tilde{}', Key('left')], 
    'tecker wide tilde': ['\\widetilde{}', Key('left')], 
    'tecker section': ['\\section{}', Key('left')], 
    'tecker sections': ['\\section*{}', Key('left')], 
    'tecker math bb': ['\\mathbb{}', Key('left')], 
    'tecker frak': ['\\frac{}', Key('left')], 
    'tecker partial': ['\\frac{\\partial}{\\partial }', Key('left')], 
    'tecker math cal': ['\\cal{}', Key('left')], 
    'tecker exp': ['\\exp{}', Key('left')], 
    'tecker subsection': ['\\subsection{}', Key('left')], 
    'tecker image': ['\\image{}', Key('left')], 
    'tecker text it': ['\\textit{}', Key('left')], 
    'tecker text': ['\\text{}', Key('left')], 
    'tecker column': ['\\column{}', Key('left')], 
    'tecker color him': ['\\column{}', Key('left')], 
    'tecker multicolumn': ['\\multicolumn{}', Key('left')], 
    'tecker multi-row': ['\\multirow{}', Key('left')], 
    'tecker underline': ['\\underline{}', Key('left')], 
    'tecker under brace': ['\\underbrace{}', Key('left')], 
    'tecker paren': ['\\paren{}', Key('left')], 
    'tecker abs': ['\\abs{}', Key('left')], 
    'tecker some': ['\\sum_{}', Key('left')], 
    'tecker set': ['\\set{}', Key('left')], 
    'tecker h space': ['\\hspace{}', Key('left')], 
    'tecker h': ['\\hspace{}', Key('left')], 
    'tecker hark': ['\\hspace{}', Key('left')], 
    'tecker park': ['\\hspace{}', Key('left')], 
    'tecker virg space': ['\\vspace{}', Key('left')], 
    'tecker verge space': ['\\vspace{}', Key('left')], 
    'tecker verge': ['\\vspace{}', Key('left')], 
    'tecker virg': ['\\vspace{}', Key('left')], 
    'tecker virgil': ['\\vspace{}', Key('left')], 
    'tecker the': ['\\vspace{}', Key('left')], 
    'tecker prod': ['\\prod{}', Key('left')], 
    'tecker overline': ['\\overline{}', Key('left')], 
    'tecker brack': ['\\brack{}', Key('left')], 
    'tecker bernoulli': ["\\text{Bern}\\left ( \\right )", Key('left'), Key('left'), Key('left'), 
                         Key('left'), Key('left'), Key('left'), Key('left'), Key('left'), 
                         Key('left'), Key('space')], 
    'tecker beta': ["\\text{Beta}\\left ( \\right )", Key('left'), Key('left'), Key('left'), 
                    Key('left'), Key('left'), Key('left'), Key('left'), Key('left'), 
                    Key('left'), Key('space')], 
    'tecker normal': ["\\mathcal{N}\\left ( \\right )", Key('left'), Key('left'), Key('left'), 
                      Key('left'), Key('left'), Key('left'), Key('left'), Key('left'), 
                      Key('left'), Key('space')], 
    'tecker exponential': ["\\text{Exp}\\left ( \\right )", Key('left'), Key('left'), Key('left'), 
                           Key('left'), Key('left'), Key('left'), Key('left'), Key('left'), 
                           Key('left'), Key('space')], 
    'tecker Poisson': ["\\text{Pois}\\left ( \\right )", Key('left'), Key('left'), Key('left'), 
                       Key('left'), Key('left'), Key('left'), Key('left'), Key('left'), 
                       Key('left'), Key('space')], 
    'tecker log normal': ["\\mathcal{LN}\\left ( \\right )", Key('left'), Key('left'), Key('left'), 
                          Key('left'), Key('left'), Key('left'), Key('left'), Key('left'), 
                          Key('left'), Key('space')], 
    'tecker gamma': ["\\Gamma\\left ( \\right )", Key('left'), Key('left'), Key('left'), 
                     Key('left'), Key('left'), Key('left'), Key('left'), Key('left'), 
                     Key('left'), Key('space')], 
    'tecker (MVN | multivariate normal)': ["\\text{MVN}\\left ( \\right )", Key('left'), Key('left'), Key('left'), 
                                   Key('left'), Key('left'), Key('left'), Key('left'), Key('left'), 
                                   Key('left'), Key('space')], 
    'tecker (stack rail | stackrel)': ['\\stackrel{}', Key('left')], 
    'tecker color': ['\\color{}', Key('left')], 
    'tecker square root': ['\\sqrt{}', Key('left')], 
    'tecker vac': ['\\vec{}', Key('left')], 
    'tecker vic': ['\\vec{}', Key('left')], 
    'tecker vec': ['\\vec{}', Key('left')], 
    
    #### latex environments
    'begin align': ['\\begin{align}\n\\end{align}', Key('up'), Key('cmd-right'), '\n'], 
    'begin aligns': ['\\begin{align*}\n\\end{align*}', Key('up'), Key('cmd-right'), '\n'], 
    'begin columns': ['\\begin{columns}\n\\end{columns}', Key('up'), Key('cmd-right'), '\n'], 
    'begin figure': ['\\begin{figure}\n\\end{figure}', Key('up'), Key('cmd-right'), '\n'], 
    'begin pmatrix': ['\\begin{pmatrix}\n\\end{pmatrix}', Key('up'), Key('cmd-right'), '\n'], 
    'begin bmatrix': ['\\begin{bmatrix}\n\\end{bmatrix}', Key('up'), Key('cmd-right'), '\n'], 
    'begin cases': ['\\begin{cases}\n\\end{cases}', Key('up'), Key('cmd-right'), '\n'], 
    'begin comment': ['\\begin{comment}\n\\end{comment}', Key('up'), Key('cmd-right'), '\n'], 
    'begin lstlisting': ['\\begin{lstlisting}\n\\end{lstlisting}', Key('up'), Key('cmd-right'), '\n'], 
    'begin center': ['\\begin{center}\n\\end{center}', Key('up'), Key('cmd-right'), '\n'], 
    'begin theorem': ['\\begin{theorem}\n\\end{theorem}', Key('up'), Key('cmd-right'), '\n'], 
    'begin definition': ['\\begin{definition}\n\\end{definition}', Key('up'), Key('cmd-right'), '\n'], 
    'begin proposition': ['\\begin{proposition}\n\\end{proposition}', Key('up'), Key('cmd-right'), '\n'], 
    'begin proof': ['\\begin{proof}\n\\end{proof}', Key('up'), Key('cmd-right'), '\n'], 
    'begin remark': ['\\begin{remark}\n\\end{remark}', Key('up'), Key('cmd-right'), '\n'], 
    'begin corollary': ['\\begin{corollary}\n\\end{corollary}', Key('up'), Key('cmd-right'), '\n'], 
    'begin tabular': ['\\begin{tabular}\n\\end{tabular}', Key('up'), Key('cmd-right'), '\n'], 
    'begin table': ['\\begin{table}\n\\end{table}', Key('up'), Key('cmd-right'), '\n'], 
    
    #### latex environments with default elements in them
    'begin enumerate': ['\\begin{enumerate}\n\\item \n\\end{enumerate}', Key('up'), Key('cmd-right'), Key('cmd-right')], 
    'begin itemize': ['\\begin{itemize}\n\\item \n\\end{itemize}', Key('up'), Key('cmd-right'), Key('cmd-right')], 
})
